version: '2'
services:
    web:
        build: ./server
        ports:
            - "5000:5000"
        depends_on:
            - "mongo"
        command: ["./wait-init.sh", "mongo", "python", "app.py"]
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017 

    indexer:
        build: ./indexer
        depends_on:
            - "mongo"
        command: ["./wait-init.sh", "mongo", "python", "app.py"]
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - CLIENT_SECRET=AzEuxi3VcfUhvynyXRZuChqQMow
            - CLIENT_ID=QrKWmDAiiMqmKg
            - USER_AGENT=reddyt

    mongo:
        image: mongo:3.0
